name: social-buying-infrastructure
services:
  infra:
    type: python:3.7
    build_as_root:
      - echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main" >> /etc/apt/sources.list
      - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
      - apt update
      - apt install ansible -y
      - wget https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
      - unzip terraform_0.12.24_linux_amd64.zip
      - mv terraform /usr/bin/
      - rm terraform_0.12.24_linux_amd64.zip
      - wget https://github.com/adammck/terraform-inventory/releases/download/v0.9/terraform-inventory_0.9_linux_amd64.zip
      - unzip terraform-inventory_0.9_linux_amd64.zip
      - mv terraform-inventory /usr/bin/
      - rm terraform-inventory_0.9_linux_amd64.zip
tooling:
  ansible:
    service: infra
    description: "Ansible"
    cmd:
      - /usr/bin/ansible -i terraform-inventory
  ansible-playbook:
    service: infra
    description: "Terraform"
    cmd:
      - /usr/bin/ansible-playbook -i terraform-inventory
  terraform:
    service: infra
    description: "Terraform"
    cmd:
      - /usr/bin/terraform
